version: '2'
services:
  xandra:
    image: cassandra
    networks:
    - todo
    container_name: xandra
    ports:
    - 7000:7000
    - 9042:9042
  todo:
    image: piskaryov/sync
    networks:
    - todo
    container_name: todo
    ports:
    - 8080:8080
    depends_on:
    - xandra
networks:
  todo:
    driver: bridge
